language: node_js

node_js:
  - 12.15.0
cache:
  directories:
    - node-modules

sudo: true

branches:
  only:
    - master

addons:
  chrome: stable
  sonarcloud:
    organization: 'deepakjhaaa-github'

before_script:
  - npm install global @angular/cli

script:
  - ng lint
  - ng test --watch false --browsers ChromeHeadless
  - ng build --prod

before_deploy: "echo 'Build is Ready.'"

deploy:
  provider: heroku
  api_key:
    secure: 'i8d9owlqH1dE0SpHBgaIl58ixqVNYMLStgWYqgsk328bgmIPNZ5Q+RiPP25LaRUBeNzPc0eP8YahoN0GPhXpwJPpzbAHRNP3/uYwfZiaGm/lvonIDv9U2z3U+RNCxbYEJ/Xla5pxtNBJt0Y5b2BJdQR6uBnxINvldv6wKjQfAUVvq0+dw+2j8+92FDTJa1owFxR3AUpEOG1Zt8rtmZz+12zrKs8EHD3k8am4RN3mhxS1Mqym9xC5GW9/y0dw9eu7SyXzgXzeXb1msCrFGVflClSCIZRu+ScsNHi7MPwAgFls+frWSkLAGmTeoA/2QGuiOWbvvh3xAJXiGAHRpi3x/UxGfpVoVuE+Lki0Mx6IrKZqgrFeWGcpf0CI1RFkdT0QYq7eOOHA0H0C5oQj1XpGi+JI8hxWMm7F4lxCjEpgTKLcyA1Ma5qp7IAQDF1SYVYhMiaeyNlDi2CB48Nj8ygHQVbWTLQX8EjbZKQ7xDLFtAG6vza4FABOtq3gtLZQ5psjnFb6bGkhvXC07+eBgwujOLwE+C6x3mT6Fdf7GkfBRzS7cIxW1e56oEVzj9+patZ/uxOz2QjuxsuuyDWMAYHtuPfihIz7752zBkxeBK+Jutprnp0ENGhaX/m4prM7okKNSaJ5Q1GOL+maCCXxhQ3LZhPi+HXgRb/fq9+P1ssen8U='

  app: ngx-tryout
  on:
    repo: DeepakJhaaa/ngx-tryout
