language: node_js

node_js:
  - '12.15.0'

cache:
  directories:
    - node-modules

sudo: true

addons:
  chrome: stable
  sonarcloud:
    organization: 'deepakjhaaa-github'
    token:
      secure: $SONAR_TOKEN

before_script:
  - npm install global @angular/cli

script:
  - ng lint
  - sonar-scanner
  - ng test --watch false --browsers ChromeHeadless
  - ng build --prod

before_deploy: "echo 'ready?'"
