language: node_js

node_js:
  - '12.15.0'

cache:
  directories:
    - node-modules

sudo: true

addons:
  chrome: stable
  sonarcloud:
    organization: 'deepakjhaaa-github'

before_script:
  - npm install global @angular/cli

script:
  - ng lint
  - ng test --watch false --browsers ChromeHeadless
  - ng build --prod

before_deploy: "echo 'Build is Ready.'"

deploy:
  provider: heroku
  api_key:
    secure: 'encrypted key goes here'
  app: ngx-tryout
  on:
    repo: DeepakJhaaa/ngx-tryout
