language: node_js

node_js:
  - '12.15.0'

cache:
  directories:
    - node-modules

sudo: true

addons:
  chrome: stable

before_script:
  - npm install global @angular/cli

before_deploy: "echo 'ready?'"
