language: node_js

node_js:
  - 12.15.0
cache:
  directories:
    - node-modules

sudo: true

addons:
  chrome: stable
  sonarcloud:
    organization: 'deepakjhaaa-github'

before_script:
  - npm install global @angular/cli

script:
  - ng lint
  - ng test --watch false --browsers ChromeHeadless
  - ng build --prod

before_deploy: "echo 'Build is Ready.'"

deploy:
  provider: heroku
  api_key:
    secure: ZualdrSgO3A4o2PhyqaOXwg9ohZiQnASdwfv1j3Ukjs0fGb6DJ5cd+L1DBIBR63X1fKnVOYUNCLma6VEA/fmPS1o/lnRlxrxhq+ufqt6RIViQS0ShmkhYEx3h+S3rrHzg3S6vhM8pX9O4z1YMs67SYUjigO9nzDUGJ3L2PBapnSVwU3ERDqvgqBmZZ1FQxn4X75WBN3yQRv+3Kh9zndEhWxVE/qoodkgeOJVNY+9Osp9hpfS3yQJlq0ijiYT8mUfpVVzeF4W5HC4p6IOfeY5K3FNMT+/Lb+fMMvHSViNlYnRzRT4IZAOPoPaQyMBxW4p2iGY4EWw1HqoTT8dkhfI++Sp9fuzUymjTBHaZFpbke67Hd7FmT+9ErEBSytnZtcbIUp5IubbWYmoyj8wGgxIEQubG1hKqtdmqeBaLgOFrbvcy1PbPffyONN8oHGLatwV7/6Zzr7Bqn+rTR9I5fxsKTRa5QVJYsG357novkM5oEOknSf6RnXWTHrDbi+/W/9mAnuw1NY8jCb2p1d1uEcNfqExAKfMiLELpJBMQoi6HqqSv/EFYsmUd3MonZhUAmjUy2vvmjVRdqeBu7G7+ypGvS5/GWSpRImLcOkqRNmJWe5Xa2wPVM45nPi3vZ/gNqF3XrfwUxbC3QkKavnznfY1jiqRca8elVnVeFhh0LyQYiA=
  app: ngx-tryout
  on:
    repo: DeepakJhaaa/ngx-tryout
